# Generated by Django 3.2.8 on 2021-10-07 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='booked_seats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[], size=25),
        ),
    ]
